=== ogcincubator/bblocks-wf4ever/build/annotated/bbr/wf4ever/wfdesc/Process/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "A computational process in a workflow",
  "type": "object",
  "properties": {
    "@type": {
      "oneOf": [
        {
          "const": "Process"
        },
        {
          "const": "Workflow"
        }
      ],
      "description": "Type identifier for a wfdesc Process or Workflow"
    },
    "@id": {
      "type": "string",
      "format": "uri",
      "description": "Unique identifier for this process"
    },
    "name": {
      "type": "string",
      "description": "Name of the process",
      "x-jsonld-id": "http://www.w3.org/2000/01/rdf-schema#label"
    },
    "description": {
      "type": "string",
      "description": "Description of what this process does",
      "x-jsonld-id": "http://www.w3.org/2000/01/rdf-schema#comment"
    },
    "hasInput": {
      "type": "array",
      "items": {
        "$ref": "https://geolabs.github.io/bblocks-wf4ever/build/annotated/bbr/wf4ever/wfdesc/Input/schema.json"
      },
      "description": "Input parameters for this process",
      "x-jsonld-id": "http://purl.org/wf4ever/wfdesc#hasInput",
      "x-jsonld-type": "@id",
      "x-jsonld-container": "@set"
    },
    "hasOutput": {
      "type": "array",
      "items": {
        "$ref": "https://geolabs.github.io/bblocks-wf4ever/build/annotated/bbr/wf4ever/wfdesc/Output/schema.json"
      },
      "description": "Output parameters produced by this process",
      "x-jsonld-id": "http://purl.org/wf4ever/wfdesc#hasOutput",
      "x-jsonld-type": "@id",
      "x-jsonld-container": "@set"
    }
  },
  "required": [
    "@type"
  ],
  "x-jsonld-extra-terms": {
    "Process": "http://purl.org/wf4ever/wfdesc#Process",
    "Input": "http://purl.org/wf4ever/wfdesc#Input",
    "Output": "http://purl.org/wf4ever/wfdesc#Output"
  },
  "x-jsonld-prefixes": {
    "wfdesc": "http://purl.org/wf4ever/wfdesc#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#"
  }
}

=== ogcincubator/bblocks-wf4ever/build/tests/bbr/wf4ever/wfdesc/Process/example_3_1.json
{
  "@type": "Process",
  "@id": "#stats-calculator",
  "name": "Statistics Calculator",
  "description": "Computes statistical metrics from raster data",
  "hasInput": [
    {
      "@type": "Input",
      "@id": "#input-raster",
      "name": "inputRaster",
      "description": "Input raster for statistical analysis"
    }
  ],
  "hasOutput": [
    {
      "@type": "Output",
      "@id": "#output-mean",
      "name": "meanValue",
      "description": "Mean pixel value"
    },
    {
      "@type": "Output",
      "@id": "#output-stdev",
      "name": "standardDeviation",
      "description": "Standard deviation of pixel values"
    },
    {
      "@type": "Output",
      "@id": "#output-histogram",
      "name": "histogram",
      "description": "Histogram of value distribution"
    }
  ]
}

=== ogcincubator/bblocks-wf4ever/build/tests/bbr/wf4ever/wfdesc/Process/example_4_1.json
{
  "@id": "https://github.com/starling-foundries/KindGrove#mangrove-analysis",
  "@type": "Process",
  "name": "Mangrove Biomass Analysis",
  "description": "Analyzes mangrove biomass using Sentinel-2 satellite imagery within a specified bounding box",
  "hasInput": [
    {
      "@id": "#input-north",
      "@type": "Input",
      "name": "north",
      "description": "Northern latitude of bounding box",
      "datatype": "float"
    },
    {
      "@id": "#input-south",
      "@type": "Input",
      "name": "south",
      "description": "Southern latitude of bounding box",
      "datatype": "float"
    },
    {
      "@id": "#input-east",
      "@type": "Input",
      "name": "east",
      "description": "Eastern longitude of bounding box",
      "datatype": "float"
    },
    {
      "@id": "#input-west",
      "@type": "Input",
      "name": "west",
      "description": "Western longitude of bounding box",
      "datatype": "float"
    },
    {
      "@id": "#input-cloud-cover",
      "@type": "Input",
      "name": "cloud_cover_max",
      "description": "Maximum acceptable cloud cover percentage",
      "datatype": "float"
    },
    {
      "@id": "#input-days-back",
      "@type": "Input",
      "name": "days_back",
      "description": "Number of days to look back for imagery",
      "datatype": "integer"
    },
    {
      "@id": "#input-output-dir",
      "@type": "Input",
      "name": "output_dir",
      "description": "Output directory name",
      "datatype": "string"
    }
  ],
  "hasOutput": [
    {
      "@id": "#output-result",
      "@type": "Output",
      "name": "result",
      "description": "Directory containing analysis results including biomass maps and statistics",
      "datatype": "Directory"
    }
  ]
}
